import React from "react";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import Navbar from "./Navbar";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </div>
    </>
  );
};

export default Layout;
