import Head from "next/head";
import Image from "next/image";
import Campaigns from "../components/Campaigns";
import MenuWrapper from "../components/products/MenuWrapper";
import Header from "../layout/Header";
import styles from "../styles/Home.module.css";
import About from "../components/About";
import Input from "../components/form/Input";
import Reservation from "../components/Reservation";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Campaigns></Campaigns>
      <MenuWrapper></MenuWrapper>
      <About></About>
      <Reservation></Reservation>
    </div>
  );
}
